### ISSUE TITLE
Colors in Source Docs Not Transferring

### ISSUE THREAD

**Issue by sierralvb** [usu-access/pilot-feedback#14]
Text colors used in source docs don't transfer over to the Pilot page. While we don't use them outside of code blocks and links (both of which have been fixed), I would imagine that many other users employ color coding to their documentation, and it would be helpful to keep it.

**Screenshots**
Color Testing Google Docs View:
![google doc colors](https://github.com/usu-accessibility/Pilot-Feedback/assets/166452991/8a1577f0-171b-46ba-9208-159c73dfbef4)

Color Testing Pilot View:
![pilot colors](https://github.com/usu-accessibility/Pilot-Feedback/assets/166452991/32e3988e-a8e5-4bdd-a8aa-34867d307dba)

[Pilot Frill Board request](https://feedback.pilot.io/b/nvk3wxmr/feature-requests/different-text-colors)

**Comment by andrew-pilot** [comment]
@sierralvb this should be fixed in our latest push. Could you confirm?

**Comment by sririe** [comment]
I've run a quick test, and the color override behavior is still occurring. Andrew is working on a fix.

**Comment by sririe** [comment]
@sierralvb @cphillipsusu A fix for this is currently in our staging environment and running through final QA. I will confirm once the fix is deployed and live.

**Comment by sririe** [comment]
@sierralvb @cphillipsusu We pushed out a fix to address colors from source docs not translating in Pilot. Barbie mode can now be activated when needed. 💅 





![Image](https://github.com/usu-accessibility/Pilot-Feedback/assets/1554080/01850da8-1b0b-405f-ba4d-8f0af30a48ec)
